version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  # Set your root password
      MYSQL_DATABASE: mydb            # Create a default database
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d  # Mount init script to create DB and tables

  flask-app:
    build:
      context: .                      # Path to your Flask app
      dockerfile: Dockerfile           # Dockerfile for the Flask app
    container_name: flask_app_container
    depends_on:
      - mysql                          # Ensure MySQL starts before Flask
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development           # Set Flask environment
      DATABASE_URL: mysql+pymysql://root:password@mysql:3306/mydb  # Database connection string
      restart: always
                      # Named volume for MySQL data persistence